# Generated by Django 4.1.7 on 2023-04-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('language', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='project',
        ),
    ]
