# Generated by Django 4.1.2 on 2023-05-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_pro_delete_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro',
            name='imgLink',
            field=models.CharField(default='default-image.jpg', max_length=2550),
        ),
    ]
